# Generated by Django 3.2.5 on 2022-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo_GB', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264, unique=True)),
                ('last_name', models.CharField(max_length=264, unique=True)),
                ('email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
