# Generated by Django 3.2.5 on 2022-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo_GB', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
    ]
