# Generated by Django 3.2.5 on 2022-02-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo_GB', '0007_auto_20220228_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
