# Generated by Django 3.2.5 on 2022-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250, unique=True)),
                ('map_url', models.TextField(max_length=500)),
                ('img_url', models.TextField(max_length=500)),
                ('location', models.TextField(max_length=250)),
                ('open_time', models.TextField(max_length=250)),
                ('closing_time', models.TextField(max_length=250)),
                ('coffee_rating', models.TextField(max_length=250)),
                ('wifi_rating', models.TextField(max_length=250)),
                ('power_rating', models.TextField(max_length=250)),
                ('seats', models.TextField(max_length=10)),
                ('has_toilet', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('coffee_price', models.FloatField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
