# Generated by Django 3.2.5 on 2022-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='closing_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='coffee_rating',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='map_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='open_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='power_rating',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='seats',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='wifi_rating',
            field=models.CharField(max_length=250),
        ),
    ]
