# Generated by Django 3.2.5 on 2022-08-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_auto_20220829_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['name']},
        ),
    ]
