# Generated by Django 3.2.5 on 2022-08-29 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cafe', '0004_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='users',
            field=models.ManyToManyField(through='Cafe.UserFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
