# Generated by Django 3.2.5 on 2022-08-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0005_cafe_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Cafe.cafe'),
        ),
    ]
